baseURL = 'http://dSm-0.github.io/'
languageCode = 'en-us'
title = 'X'
theme = "yinyang"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "?"
#  homepage = "https://joway.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.jp]
    contentDir = "content/jp"
    languageName = "Japanese"
    weight = 1

[params]
disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://joway.io"
